#!/usr/bin/env python3

import sys
import os

argc = len(sys.argv)
argv = sys.argv
with open('.facing', 'r') as f:
    facing = f.read().strip()

def getDir(dir):
    directions = ['n', 'e', 's', 'w']
    i = directions.index(facing)
    if dir=='left':
        return directions[(i+3) % 4]
    elif dir=='right':
        return directions[(i+1) % 4]
    elif dir=='back':
        return directions[(i+2) % 4]
    else:
        return facing

if argc==1 or (argc==2 and sys.argv[1]=='ahead'):
    targetDir = getDir('ahead')

elif argc==2:
    targetDir = getDir(argv[1])

with open('.facing', 'w') as f:
    f.write(targetDir + '\n')
