var flowerNames = [	
	"Acacia",
	"Agapanthus",
	"Allium",
	"Alstroemeria",
	"Amaranthus",
	"Amaryllis",
	"Anemone",
	"Anthurium",
	"Aster",
	"Babys Breath",
	"Banksia",
	"Bells of Ireland",
	"Bird of Paradise",
	"Boronia",
	"Bouvardia",
	"Calla",
	"Canterbury Bells",
	"Carnation",
	"Cattleya Orchids",
	"Celosia",
	"Chrysanthemum",
	"Cornflower",
	"Craspedia",
	"Crocosmia",
	"Cymbidium Orchids",
	"Dahlia",
	"Delphinium",
	"Dendrobium Orchids",
	"Forsythia",
	"Freesia",
	"Gardenia",
	"Genista",
	"Gerbera",
	"Ginger",
	"Gladiolus",
	"Gloriosa",
	"Heather",
	"Hyacinth",
	"Hydrangeas",
	"Hypericum",
	"Iris",
	"Kangaroo Paw",
	"King Protea",
	"Liatris",
	"Lilac",
	"Lily",
	"Lily of the Valley",
	"Lisianthus",
	"Muscari",
	"Nerine",
	"Oncidium Orchids",
	"Orchids",
	"Peony",
	"Phlox",
	"Pincushion",
	"Pitcher Plant",
	"Queen Annes Lace",
	"Rice Flower",
	"Rose",
	"Safflower",
	"Sandersonia",
	"Snapdragon",
	"Solidago",
	"Statice",
	"Stephanotis",
	"Stock",
	"Sunflower",
	"Sweet Pea",
	"Tulip",
	"Waxflower",
	"Zinnia"
	];


var cleatNames = [
	"Nike Force Zoom Trout 6",
	"Nike Force Air Trout 6 Pro",
	"Nike Force Trout 6 Pro MCS",
	"Nike Force Zoom Trout 6 Keystone",
	"Nike Force Trout 6 Pro MCS",
	"Nike Force Trout 6 Keystone",
	"Nike Force Zoom Trout 6 Turf",
	"Nike Force Zoom Trout 6 Turf Premium",
	"Nike Force Zoom Trout 5",
	"Nike Alpha Huarache Elite 2 Low",
	"Nike Alpha Huarache Varsity Turf",
	"NIKE ALPHA HUARACHE MID BY YOU",
	"NIKE ALPHA HUARACHE MID BY YOU",
	"NIKE ALPHA HUARACHE LOW BY YOU",
	"NIKE ALPHA HUARACHE ELITE MID PREMIUM BY YOU",
	"NIKE ALPHA HUARACHE ELITE LOW PREMIUM BY YOU",
	"Nike Alpha Huarache Elite 2 Low",
	"Nike Alpha Huarache Turf",
	"NIKE ALPHA HUARACHE ELITE LOW PREMIUM BY YOU",
	"Nike Alpha Huarache Elite 2 Low MCS",
	"NIKE ALPHA HUARACHE LOW BY YOU",
	"NIKE ALPHA HUARACHE ELITE MID PREMIUM BY YOU",
	"Nike Lunar Hyperdiamond 2 Pro",
	"Nike Vapor Ultrafly 2 Keystone"
];


var descriptions = [

	"The Nike Force Zoom Trout 6 is inspired by Mike Trout's legendary 5-tool play. The lightweight upper helps stabilize your foot in key areas while angular spikes on the sole give you traction to tear up the base paths.",
	"The Nike Force Air Trout 6 Pro is inspired by Mike Trout's legendary play. Its molded upper helps stabilize your foot during dynamic movement. Angular spikes add traction for running the basepaths.",
	"The Nike Force Trout 6 Pro MCS combines stability and comfort for game-day performance. A durable molded upper has a midfoot strap to help secure your foot. An aggressive cleat pattern delivers multi-directional traction. Arrowhead details at the strap nod to Mike Trout's love of hunting.",
	"The Nike Force Zoom Trout 6 Keystone is inspired by Mike Trout's speed and power. It keeps you in the game with a durable upper and comfortable foam cushioning. A rubber outsole gives you traction for the basepaths.",
	"The Nike Force Trout 6 Pro MCS combines stability and comfort for game-day performance. A durable molded upper has a midfoot strap to help secure your foot. An aggressive cleat pattern delivers multi-directional traction.",
	"The Nike Force Trout 6 Keystone is inspired by Mike Trout's speed and power. Stay in the game with a durable upper and comfortable foam cushioning. A rubber sole gives you traction for the basepaths. Arrowhead details at the strap nod to Mike Trout's love of hunting.",
	"The Nike Force Zoom Trout 6 Turf is built for your pregame routine. Durable molded material and a midfoot strap help keep your foot ventilated and secure when you're taking batting practice or shagging fly balls before first pitch.",
	"The Nike Force Zoom Trout 6 Turf Premium adds patriotic flair to your pregame routine. Its lightweight molded upper helps stabilize your foot, and a nubby outsole delivers traction on a variety of surfaces.",
	"The Nike Force Zoom Trout 5 is inspired by Mike Trout's legendary 5-tool play. The molded upper helps stabilize your foot in key areas, and angular spikes on the outsole give you traction to tear up the basepaths.",
	"A true alpha takes command of the diamond when the competition heats up. The Nike Alpha Huarache Elite 2 Low sports a 9-stud design that lets you dig into the batter's box and tear up the basepaths like a pro. Underfoot, a Nike Air and Zoom Air unit deliver plush cushioning to keep your feet comfortable all season long.",
	"The Nike Alpha Huarache Varsity Turf features the durability of a synthetic leather upper and the underfoot cushioning of Lunarlon foam. Its aggressive rubber outsole pattern provides traction on all pre-game surfaces including grass, dirt, turf and rubber.",
	"Start your championship season on the right foot with the Nike Alpha Huarache Mid By You. Before lacing up in these cleats, customize them with colors, traction and personalization for a look that stands out in the batter's box and on the basepaths.",
	"Start your championship season on the right foot with the Nike Alpha Huarache Mid By You. Before lacing up in these cleats, customize them with colors, traction and personalization for a look that stands out in the batter's box and on the basepaths.",
	"Start your championship season on the right foot with the Nike Alpha Huarache Low By You. Before lacing up in these cleats, customize them with colors, traction and personalization for a look that stands out in the batter's box and on the basepaths.",
	"The Nike Alpha Huarache Elite Mid Premium By You¬†lets you swing for the fences by crafting your perfect cleat. Start with Nike Air and Zoom Air for a double dose of cushioning, then customize the colors, traction, premium materials and personalized details.",
	"The Nike Alpha Huarache Elite Low Premium By You¬†lets you swing for the fences by crafting your perfect cleat. Start with Nike Air and Zoom Air for a double dose of cushioning, then customize the colors, traction, premium materials and personalized details.",
	"Built for containment and comfort on the field, the Nike Alpha Huarache Elite 2 Low features both a Nike Air and Zoom Air unit for optimal underfoot cushioning. Its 9-stud design gives you traction and stability, offering you the versatility needed to excel at every position.",
	"The Nike Alpha Huarache Turf features synthetic leather and a foam sole for durability and lightweight support on the diamond. The rubber outsole pattern provides traction on surfaces such as grass, dirt, turf and rubber.",
	"The Nike Alpha Huarache Elite Low Premium By You¬†lets you swing for the fences by crafting your perfect cleat. Start with Nike Air and Zoom Air for a double dose of cushioning, then customize the colors, traction, premium materials and personalized details.",
	"Built for containment and comfort on the field, the Nike Alpha Huarache Elite 2 Low MCS features both a Nike Air unit and Zoom Air unit for optimal underfoot cushioning. Its 11-stud design gives you traction and stability, offering you the versatility needed to excel at every position.",
	"Start your championship season on the right foot with the Nike Alpha Huarache Low By You. Before lacing up in these cleats, customize them with colors, traction and personalization for a look that stands out in the batter's box and on the basepaths.",
	"The Nike Alpha Huarache Elite Mid Premium By You¬†lets you swing for the fences by crafting your perfect cleat. Start with Nike Air and Zoom Air for a double dose of cushioning, then customize the colors, traction, premium materials and personalized details.",
	"The Nike Lunar Hyperdiamond 2 Pro Women's Softball Cleat provides lightweight cushioning and ground-gripping traction to optimize speed in the field and around the bases.",
	"Built for multidirectional movement, the Nike Vapor Ultrafly 2 Keystone will keep you light on your feet. It features an asymmetrical tongue and laces for lateral support while rounding bases and a 12-stud configuration for powerful traction.",
	"Acacias were first described in Africa in 1733, since then they spread from Europe, Africa, Asia to the Americas. Acacia makes an excellent garden plant.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. It has large, round heads covered with blue or white tubular flowers. The Agapanthus derives its name from the Greek words for 'love' and 'flower'.",
	"Since Victorian times, a special meaning has been attached to flowers. The genus Allium have been prized since ancient times for their medicinal and culinary qualities. Growing to 4 or 5 feet tall with white, blue, lavender or purple snowball-shaped inflorescences atop bare stems.",
	"Since Victorian times, a special meaning has been attached to flowers.It's originally from the South American origin, which was later brought to Europe in the 18th century making it now grow internationally.",
	"A native of South America, the amananthus' name is derived from the Greek amarantos, which means 'unfading' and is an appropriate reference to the flower's long-lasting deep red, green or yellow blooms.¬†Many parts of the plants, including the leaves and seeds, are edible, and are frequently used as a source of food in India and South America.",
	"History of Amaryllis: Since Victorian times, a special meaning has been attached to flowers. Amaryllis blooms are huge, trumpet-shaped flowers clustered atop stately long, leafless stems. This flowers are traditionally sold during the winter holidays ‚Äì both as cut flowers and packaged in potted bulb kits.",
	"Since Victorian times, a special meaning has been attached to flowers.In Greek mythology, the anemone symbolized the bloody death of the Greek god Adonis. Bereaved, Aphrodite is said to have used the blood-red anemone to preserve his memory and greet new life in the spring.",
	"Anthuriums are commonly called flamingo flowers or tailflowers, which include more than 600 flower species native around the entire tropical U.S. regions. Their genus name, Anthurium, comes from the Greek words anthos meaning 'flower,' and oura, meaning 'tail.'",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. A member of the Asteraceae family, the aster takes its name from the Latin word meaning 'star' and refers to the flower's starlike head.",
	"Since Victorian times, a special meaning has been attached to flowers. European and Northern Asian origins and is a relative of carnations.The baby's breath is used primarily as a filler flower, and is available in both white and pink varieties.",
	"Banksias are members of the Proteaceae family, and are indigenous to South Africa and Australia.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Native to western Asia, the genus Moluccella gets its name from the Indonesian Molucca Islands, which were once mistakenly thought to be the flower's native land.",
	"Strelitzia is a genus of four species which are native to South Africa. The genus is known as the bird of paradise because of its resemblance to the bird which shares its name.",
	"This evergreen shrub is a native of Australia and Tasmania. It is named in honor of Francesco Borone, a personal servant who died in 1794 while collecting a plant for botanist John Sibthorp.",
	"Of the more than 30 bouvardia species known, most are shrubs and herbs native to Mexico and Central America.¬†The genus is named in honor of Charles Bouvard (1572‚Äì1658), physician to Louis XIII",
	"Calla's are natives of South Africa, they grow so abundantly that they're viewed as common roadside plants and are called 'pig ears.'",
	"Campanula medium originates in southern Europe.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Carnations are no exception and are the symbolic flower of Mother's Day. Carnations have many flower meanings often associated with a particular color.",
	"Cattleya is a genus of approximately 53 species from Mexico to South America. The species was named after William Cattley in 1824 who successfully cultivaed the earliest specimens.",
	"Celosia's name is derived from the Greek word for 'burning.'¬†It grows widespread across Mexico, where it is known as 'Velvet flower', northern South America, tropical Africa, the West Indies, South, East and Southeast Asia where it is grown as a native or naturalized wildflower, and is cultivated as a nutritious leafy green vegetable. It is traditional fare in the countries of Central and West Africa, and is one of the leading leafy green vegetables in Nigeria, where it is known as ‚Äòsoko yokoto', meaning 'make husbands fat and happy'.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Native to Europe, Asia and South Africa, chrysanthemums are aromatic annual and perennial herbs.",
	"The Bachelor Button is a native of the Mediterranean region and the Near East. In folklore, cornflowers were worn by young men in love; if the flower faded too quickly, it was taken as a sign that the man's love was not returned. It was the favorite flower of John F. Kennedy and was worn by his son, John F. Kennedy, Jr. at his wedding in tribute to his father.",
	"Known familiarly as the 'billy button' or 'drumstick,' Craspedia is a native wildflower of New Zealand, Australia and Tasmania. It has been cultivated in the United States as a garden flower ever since 1988.Its name comes from the Greek kraspedon for 'edging,'¬†referring ¬†to the feathery foliage that accompanies its fruit.",
	"Crocosmia is native to the grasslands of Cape Floristic Region, South Africa.",
	"They have been cultivated for thousands of years, especially in China. Cymbidiums became popular in Europe during the Victorian era. One feature that makes the plant so popular is the fact that it can survive during cold temperatures.",
	"There are two legends of note about the origins of the daffodil, each being very different. It seems this flower has different meanings for different cultures of the world. For the West, it's vanity, and the East it means fortune and prosperity.",
	"Dahlias are native to Mexico and Central America.The first dahlias cultivated outside their native environment and were then grown in Madrid, Spain, in the late 1700s. Dahlias are members of the Compositae family, and are related to daisies.",
	"The Delphinium family¬†includes more than 300 species of flowers native to the northern hemisphere.¬†They are often called larkspur because of their unusual spur-like flowers. The Delphinium has become a florist favorite because it is one of the few, large flowers that are actually natural blue.",
	"Since Victorian times, a special meaning has been attached to flowers. The flowers are native to Southeast Asia, Japan, Taiwan, Indonesia, China, the Philippines and Australia. Their name derives from the Greek word kymbe, meaning 'boat,' and refers to the blooms' hollowed lips.",
	"Forsythia are deciduous shrubs with rough grey-brown bark.¬†The bright, yellow flowers are produced in the early spring before the leaves.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Freesias are native to South Africa and are named for Friedrich Heinrich Theodor Freese, a German student who studied African plants in the 19th century.",
	"The double-flowered Gardenia originated in south China, while Gardenia thunbergia, which has single, strap-petalled flowers, is from South Africa.¬†Jazz singer Billie Holiday was known to wear gardenias in her hair, one of her most noticeable features. She called them her trademark.",
	"Genista is native to Africa, specifically the Canary Islands, thus the nickname Canary Island Broom. Plants were used to make a green dye.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Gerbera's are a native to South Africa and Asia, they are available in many colors. Gerbera's have light or dark colored centers and come in standard or mini sizes.",
	"About 50 species occur in tropical and subtropical regions.The sweetly scented flowers are borne in spirally arranged clusters.",
	"The word gladiolus means 'little sword' in Latin. The first of the 250-300 existing gladiolus species originated in South Africa and the Mediterranean region. The flower was then later brought to Europe, where it is bearing almost every color except true blue.",
	"Gloriosa is native to Africa, Southeastern Asia and parts of Malaysia, but they are now widely cultivated. All parts of this plant are toxic.",
	"The Heather genus includes more than 500 species of evergreen plants native primarily to South Africa, but also to Europe and Turkey.",
	"Hyacinths are sometimes associated with rebirth and the Greek god Apollo. The Hyacinth flower is used in the Haftseen table setting for the Persian New Year celebration Norouz held during the Spring Equinox.",
	"Hydrangeas originated in North America, South America and Asia. Their name comes from the Greek words hydor, which means 'water,' and aggeion, which means 'vessel,' referring to the shape of the flowers' seed caps. The Hydrangea florets' rounded shapes have gained them popularity in recent years.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower color is a symbolic representation of an emotion or expression. Iris's are native to southern Europe and the Mediterranean region.The Iris takes its name from the Greek goddess who transported messages between mortals and the Mount Olympus.",
	"The tubular flowers are coated with dense hairs and open with six claw-like structures, thus the common name 'Kangaroo Paw.' As its common name suggests, kangaroo paw is a native of southwestern Australia.",
	"The King Protea is the National Flower of South Africa. Proteas come in a variety of sizes and colors and are members of the Proteaceae family, a genus of 130 species of African shrubs. The flowers' name, therefore, refers to the flower heads' varied forms.",
	"Liatris is native to North America, Mexico, and the Bahamas.",
	"Since Victorian times, a special meaning has attached to flowers. Native to Europe and the temperate zones of Asia, lilacs are popular spring flowers, prized for their delicate blooms and their heady fragrance.",
	"A member of the Liliaceae family, lilies are fragrant, bulbous, herbaceous perennials that are native to the northern temperate zones. About half of the lily species originate in continental Asia, while the remainder are native to Europe, North America and Japan. In ancient times, many cultures considered lilies to be signs of fertility and a pure life, and the flowers were used as offerings to appease the gods.",
	"In the wild, lilies of the valley can be found throughout much of temperate Europe. A Christian legend states that Mary's tears turned to lily of the valley when she cried at the crucifixion of Jesus.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. It originates in the West Indies, Mexico, and Central and South America. The common name comes from the Greek words lysis, meaning 'dissolution,' and anthos, meaning 'flower'.",
	"The Muscari have originated in the old world, from the Mediterranean basin, the Center and South of Europe, Northern Africa, the West, Center and South-West of Asia. The term muscari comes from the Latin muscus, since the scent is said to resemble musk.",
	"Nerine was named when a ship was wrecked many years ago on Guernsey, the second largest of the Channel Islands, located off the coast of Normandy. They are actually native only to South Africa, where they bloom every March on Table Mountain in Cape Town.",
	"The flowers are native to Southeast Asia, Japan, Taiwan, Indonesia, China, the Philippines and Australia. Their name derives from the Greek word kymbe, meaning 'boat,' and refers to the blooms' hollowed lips.",
	"The orchid family is currently believed to be the largest family of flowering plants. The number of orchid species equals more than twice the number of bird species, and about four times the number of mammal species.",
	"Peonies are native to Asia, southern Europe and western North America.",
	"The name phlox is a Latin word for 'flower' or 'flame,' which comes from the Greek word meaning 'wallflower', and is a native North American plant.",
	"Pincushions are native to Zimbabwe and South Africa, where they occupy a variety of habitats, including scrub, forest, and mountain slopes.",
	"The pitcher plant is actually native to the New World. Its range extends from southern Alabama, through Florida and Georgia, to the coastal plains of southern Virginia, North Carolina and South Carolina.",
	"In ancient Egypt, this plant was used to treat skin diseases. Ammi majus is being studied for potential cancer and AIDS treatments.",
	"The name refers not to the flowers' appearance, but to the moist environments in which they typically grow.These flower have gently bending stems covered with soft, fuzzy hair and sparse foliage support.",
	"Native to east Australia.",
	"These timelessly beautiful blooms originated more than 4,000 years ago, growing in the fertile land between the Tigris and Euphrates rivers in the Middle East. Today, roses come in many shapes, sizes and colors, including three popular types: sweetheart, spray and tea.",
	"Safflower is one of humanity's oldest crops. Dyes and garlands made from safflowers were found in the tomb of the pharaoh Tutankhamun.",
	"Sandersonia is a plant genus native to South Africa.",
	"Originating in southern Europe, this flower's name also translates to 'mournful widow.'",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. A highly versatile, spiky flower that comes from the Mediterranean area.",
	"Solidago is native to North America, although some varieties are native to South America or Europe. Solidago derives its name from the Latin words solido, which means 'to strengthen or make whole,' and ago, which means 'to make.' The name refers to the medicinal properties attributed to the flowers.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. Of the Mediterranean origin, limonium‚Äìcommonly called statice‚Äìgets its name from the Greek word for 'meadow'.",
	"Stephanotis is native from Malaya to Madagascar. The name derives from the Greek ‚Äòstephanos' crown and ‚Äòotis' ear which refers to the arrangement of the stamens in the flower which (supposedly) are ear shaped.",
	"Since Victorian times, a special meaning has been attached to flowers. Each flower or flower color is a symbolic representation of an emotion or expression. The stock's specific epithet, incana, means 'hoary' and refers to the plant's typically fuzzy stem.",
	"A native of North America, the sunflower is best-known for its bold cheery flowers.",
	"With more than 260 varieties in cultivation, sweet peas come in a broad color range, including white, purple, pink, lavender and red.",
	"Tulips have a long interesting history. Grown for years in Turkish gardens, tulips were introduced to Europe in the mid-16th century. Tulipa, the tulip's genus name, is the Latinized version of tulipam or tulbend, which means 'turban' in Turkish and was generally used to describe the tulips' shapes.",
	"The name uncinatum means 'hooked' in Latin, in reference to the tips of the leaves.",
	"Zinnias are simple, cheery garden flowers that are related to the black-eyed Susan, marigold and aster. It's part of the Asteraceae family and is native to the Americas, including Mexico, Colorado, New Mexico, Kansas, Arizona and Texas. It's been commonly referred to as youth and old age, in reference to the flower's multiple layers."



];